# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perifericos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from memoria import Ui_Memoria
from gpio import Ui_GPIO
from uart import Ui_UART
from acelerador import Ui_Acelerador

class Ui_Perifericos(object):
    def openMemoria(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Memoria()
        self.ui.setupUi(self.window)
        self.window.show()

    def openGpio(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GPIO()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openUart(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_UART()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAceleradores(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Acelerador()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Perifericos):
        Perifericos.setObjectName("Perifericos")
        Perifericos.resize(262, 281)
        self.centralwidget = QtWidgets.QWidget(Perifericos)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Memoria = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openMemoria())
        self.Memoria.setGeometry(QtCore.QRect(20, 50, 221, 25))
        self.Memoria.setObjectName("Memoria")
        self.GPIO = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openGpio())
        self.GPIO.setGeometry(QtCore.QRect(20, 90, 221, 25))
        self.GPIO.setObjectName("GPIO")
        self.UART = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openUart())
        self.UART.setGeometry(QtCore.QRect(20, 130, 221, 25))
        self.UART.setObjectName("UART")
        self.Acelerador = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openAceleradores())
        self.Acelerador.setGeometry(QtCore.QRect(20, 170, 221, 25))
        self.Acelerador.setObjectName("Acelerador")
        self.Voltar = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: Perifericos.close())
        self.Voltar.setGeometry(QtCore.QRect(20, 210, 221, 25))
        self.Voltar.setObjectName("Voltar")
        Perifericos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Perifericos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 262, 22))
        self.menubar.setObjectName("menubar")
        Perifericos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Perifericos)
        self.statusbar.setObjectName("statusbar")
        Perifericos.setStatusBar(self.statusbar)

        self.retranslateUi(Perifericos)
        QtCore.QMetaObject.connectSlotsByName(Perifericos)

    def retranslateUi(self, Perifericos):
        _translate = QtCore.QCoreApplication.translate
        Perifericos.setWindowTitle(_translate("Perifericos", "Periféricos"))
        self.label.setText(_translate("Perifericos", "Periféricos"))
        self.Memoria.setText(_translate("Perifericos", "Controlador de Memória"))
        self.GPIO.setText(_translate("Perifericos", "GPIO"))
        self.UART.setText(_translate("Perifericos", "UART"))
        self.Acelerador.setText(_translate("Perifericos", "Aceleradores"))
        self.Voltar.setText(_translate("Perifericos", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Perifericos = QtWidgets.QMainWindow()
    ui = Ui_Perifericos()
    ui.setupUi(Perifericos)
    Perifericos.show()
    sys.exit(app.exec_())
