# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plataforma.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from processador import Ui_Processador
from barramento import Ui_Barramento
from perifericos import Ui_Perifericos
from software import Ui_Software
from gerador_top_vhd import Gerador_Vhdl
#from load import Ui_SalvarCarregar 

class Ui_Plataforma(object):
    def __init__(self):
        self.path = None

    def openProcessador(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Processador()
        self.ui.setupUi(self.window)
        self.window.show()

    def openBarramento(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Barramento()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPerifericos(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Perifericos()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSoftware(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Software()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openLoad(self):
        nomeload = QFileDialog.getOpenFileName(None, 'Open a File', '', 'Ini(*.ini)')
        self.path = nomeload[0]

    def gerar_vhdl(self, Plataforma):
        if not self.path:
            nomesave = QFileDialog.getSaveFileName(None, 'Save a File', '', 'Vhd(*.vhd)')
            nome_arq = nomesave[0] + '.vhd'
            destino_arq = open(nome_arq, 'w')
            destino_arq.close()
            self.vhdl = Gerador_Vhdl()
            self.vhdl.gera_vhdl(nome_arq, '/home/carlos/plataforma/config.ini')
        else:
            nomesave = QFileDialog.getSaveFileName(None, 'Save a File', '', 'Vhd(*.vhd)')
            nome_arq = nomesave[0] + '.vhd'
            destino_arq = open(nome_arq, 'w')
            destino_arq.close()
            self.vhdl = Gerador_Vhdl()
            self.vhdl.gera_vhdl(nome_arq, self.path)

        Plataforma.close()

    def setupUi(self, Plataforma):
        Plataforma.setObjectName("Plataforma")
        Plataforma.resize(509, 288)
        self.centralwidget = QtWidgets.QWidget(Plataforma)
        self.centralwidget.setObjectName("centralwidget")
        self.Processador = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openProcessador())
        self.Processador.setGeometry(QtCore.QRect(10, 10, 221, 71))
        self.Processador.setObjectName("Processador")
        self.Barramento = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openBarramento())
        self.Barramento.setGeometry(QtCore.QRect(10, 90, 221, 71))
        self.Barramento.setObjectName("Barramento")
        self.Perifericos = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openPerifericos())
        self.Perifericos.setGeometry(QtCore.QRect(270, 90, 221, 71))
        self.Perifericos.setObjectName("Perifericos")
        self.Software = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSoftware())
        self.Software.setGeometry(QtCore.QRect(270, 10, 221, 71))
        self.Software.setObjectName("Software")
        self.save_load = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openLoad())
        self.save_load.setGeometry(QtCore.QRect(10, 170, 221, 71))
        self.save_load.setObjectName("save_load")
        self.Sair = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.gerar_vhdl(Plataforma))
        self.Sair.setGeometry(QtCore.QRect(270, 170, 221, 71))
        self.Sair.setObjectName("Sair")
        Plataforma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Plataforma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 22))
        self.menubar.setObjectName("menubar")
        Plataforma.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Plataforma)
        self.statusbar.setObjectName("statusbar")
        Plataforma.setStatusBar(self.statusbar)

        self.retranslateUi(Plataforma)
        QtCore.QMetaObject.connectSlotsByName(Plataforma)

    def retranslateUi(self, Plataforma):
        _translate = QtCore.QCoreApplication.translate
        Plataforma.setWindowTitle(_translate("Plataforma", "Plataforma"))
        self.Processador.setText(_translate("Plataforma", "Configurações do Processador"))
        self.Barramento.setText(_translate("Plataforma", "Configurações do Barramento"))
        self.Perifericos.setText(_translate("Plataforma", "Configurações dos Periféricos"))
        self.Software.setText(_translate("Plataforma", "Configurações do Software"))
        self.save_load.setText(_translate("Plataforma", "Carregar Arquivo"))
        self.Sair.setText(_translate("Plataforma", "Gerar Vhdl"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Plataforma = QtWidgets.QMainWindow()
    ui = Ui_Plataforma()
    ui.setupUi(Plataforma)
    Plataforma.show()
    sys.exit(app.exec_())
