# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plataforma.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
from subprocess import Popen
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from processador import Ui_Processador
from barramento import Ui_Barramento
from perifericos import Ui_Perifericos
from software import Ui_Software
from gerador_top_vhd import Gerador_Vhdl

class Ui_Plataforma(object):
    def __init__(self):
        self.path = None
        self.nome_arq = None

    def openProcessador(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Processador()
        self.ui.setupUi(self.window)
        self.window.show()

    def openBarramento(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Barramento()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPerifericos(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Perifericos()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSoftware(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Software()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openLoad(self):
        nomeload = QFileDialog.getOpenFileName(None, 'Open a File', '', 'Ini(*.ini)')
        self.path = nomeload[0]

    def msgButtonClick(self, i):
        return i.text()

    def gerar_vhdl(self, Plataforma):
        caminho_arq = sys.argv[0]
        caminho_arq = os.path.abspath(caminho_arq)
        caminho_dir = os.path.dirname(caminho_arq)
        self.nome_arq = str(QtWidgets.QFileDialog.getExistingDirectory())
        self.vhdl = Gerador_Vhdl()

        if not self.nome_arq:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Nenhuma Pasta foi selecionada")
            msgBox.setWindowTitle("Aviso")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(self.msgButtonClick)

            returnValue = msgBox.exec()
            if returnValue == QMessageBox.Ok:
                print('Finalizado sem sucesso!')
        else:
            if not self.path:
                self.vhdl.gera_vhdl(self.nome_arq, caminho_dir + '/config.ini', None)
            else:
                self.vhdl.gera_vhdl(self.nome_arq, caminho_dir + '/config.ini', self.path)

            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText(f"Arquivo VHDL salvo em: {self.nome_arq}/SoC/")
            msgBox.setWindowTitle("Aviso")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(self.msgButtonClick)

            returnValue = msgBox.exec()
            if returnValue == QMessageBox.Ok:
                print('Finalizado com sucesso!')

        #Plataforma.close()

    def openSim(self):
        os.chdir(f'{self.nome_arq}/SoC/')
        Popen(["gnome-terminal", "-e", 'sh -c "make vivado-ahx-sim; sleep 10"'])
    
    def openSint(self):
        os.chdir(f'{self.nome_arq}/SoC/fpga/zedboard/')
        Popen(["gnome-terminal", "-e", 'sh -c "make create-project; sleep 10; make bitstream; sleep 10; make fpga; sleep 10; make zedboard-run; sleep 10"'])

    def setupUi(self, Plataforma):
        Plataforma.setObjectName("Plataforma")
        Plataforma.resize(509, 401)
        self.centralwidget = QtWidgets.QWidget(Plataforma)
        self.centralwidget.setObjectName("centralwidget")
        self.Processador = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openProcessador())
        self.Processador.setGeometry(QtCore.QRect(10, 10, 221, 71))
        self.Processador.setObjectName("Processador")
        self.Barramento = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openBarramento())
        self.Barramento.setGeometry(QtCore.QRect(10, 90, 221, 71))
        self.Barramento.setObjectName("Barramento")
        self.Perifericos = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openPerifericos())
        self.Perifericos.setGeometry(QtCore.QRect(270, 90, 221, 71))
        self.Perifericos.setObjectName("Perifericos")
        self.Software = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSoftware())
        self.Software.setGeometry(QtCore.QRect(270, 10, 221, 71))
        self.Software.setObjectName("Software")
        self.save_load = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openLoad())
        self.save_load.setGeometry(QtCore.QRect(10, 170, 221, 71))
        self.save_load.setObjectName("save_load")
        self.Sair = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.gerar_vhdl(Plataforma))
        self.Sair.setGeometry(QtCore.QRect(270, 170, 221, 71))
        self.Sair.setObjectName("Sair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 330, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Sim = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSim())
        self.Sim.setGeometry(QtCore.QRect(10, 250, 221, 71))
        self.Sim.setObjectName("Sim")
        self.Sint = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSint())
        self.Sint.setGeometry(QtCore.QRect(270, 250, 221, 71))
        self.Sint.setObjectName("Sint")
        Plataforma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Plataforma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 22))
        self.menubar.setObjectName("menubar")
        Plataforma.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Plataforma)
        self.statusbar.setObjectName("statusbar")
        Plataforma.setStatusBar(self.statusbar)

        self.retranslateUi(Plataforma)
        QtCore.QMetaObject.connectSlotsByName(Plataforma)

    def retranslateUi(self, Plataforma):
        _translate = QtCore.QCoreApplication.translate
        Plataforma.setWindowTitle(_translate("Plataforma", "Plataforma"))
        self.Processador.setText(_translate("Plataforma", "Configurações do Processador"))
        self.Barramento.setText(_translate("Plataforma", "Configurações do Barramento"))
        self.Perifericos.setText(_translate("Plataforma", "Configurações dos Periféricos"))
        self.Software.setText(_translate("Plataforma", "Configurações do Software"))
        self.save_load.setText(_translate("Plataforma", "Salvar/Carregar Alterações"))
        self.Sair.setText(_translate("Plataforma", "Gerar Vhdl"))
        self.label.setText(_translate("Plataforma", "As configurações estão sendo salvas no arquivo \"config.ini\" "))
        self.Sim.setText(_translate("Plataforma", "Simulação"))
        self.Sint.setText(_translate("Plataforma", "Sintetização"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Plataforma = QtWidgets.QMainWindow()
    ui = Ui_Plataforma()
    ui.setupUi(Plataforma)
    Plataforma.show()
    sys.exit(app.exec_())
