#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 10 17:44:35 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto da5345bda08540c69cbc1279aaca1f2f --incr --debug off --relax --mt 8 -generic_top "AHX_FILEPATH=/home/carlos/plataforma/SoC/software/out/app-sim.ahx" -generic_top "MEM_SIZE_MB=8" -L xil_defaultlib -L secureip --snapshot ahx_tb_behav xil_defaultlib.ahx_tb -log elaborate.log"
xelab -wto da5345bda08540c69cbc1279aaca1f2f --incr --debug off --relax --mt 8 -generic_top "AHX_FILEPATH=/home/carlos/plataforma/SoC/software/out/app-sim.ahx" -generic_top "MEM_SIZE_MB=8" -L xil_defaultlib -L secureip --snapshot ahx_tb_behav xil_defaultlib.ahx_tb -log elaborate.log

