#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 10 17:47:46 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ahx_tb_behav -key {Behavioral:sim_1:Functional:ahx_tb} -tclbatch ahx_tb.tcl -log simulate.log"
xsim ahx_tb_behav -key {Behavioral:sim_1:Functional:ahx_tb} -tclbatch ahx_tb.tcl -log simulate.log

